"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase-client";
import { useRouter } from "next/navigation";
import { 
  Briefcase, 
  MapPin, 
  DollarSign, 
  Clock, 
  Building2, 
  Loader2, 
  Save, 
  X,
  Eye
} from "lucide-react";
import { cn } from "@/lib/utils";

export default function PostJobForm({ companyId, companyName }: { companyId: string, companyName: string }) {
  const supabase = createClient();
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    title: "",
    description: "",
    location: "Remote",
    salary_range: "",
    job_type: "full-time",
    work_mode: "remote",
    experience_level: "mid",
    skills_required: [] as string[]
  });
  const [skillInput, setSkillInput] = useState("");

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const addSkill = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && skillInput.trim()) {
      e.preventDefault();
      if (!formData.skills_required.includes(skillInput.trim())) {
        setFormData({ 
          ...formData, 
          skills_required: [...formData.skills_required, skillInput.trim()] 
        });
      }
      setSkillInput("");
    }
  };

  const removeSkill = (skillToRemove: string) => {
    setFormData({ 
      ...formData, 
      skills_required: formData.skills_required.filter(s => s !== skillToRemove) 
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const { error } = await supabase
        .from('jobs')
        .insert({
          company_id: companyId,
          title: formData.title,
          description: formData.description,
          location: formData.location,
          salary_range: formData.salary_range || "Not Disclosed",
          job_type: formData.job_type,
          work_mode: formData.work_mode,
          experience_level: formData.experience_level,
          skills_required: formData.skills_required,
          // embedding: will be generated by a trigger or separate process later
        });

      if (error) throw error;

      router.push("/recruiter/my-jobs");
      router.refresh();
    } catch (error: any) {
      console.error("Error posting job:", error);
      alert("Failed to post job: " + error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="grid lg:grid-cols-2 gap-8">
      {/* Form */}
      <form onSubmit={handleSubmit} className="space-y-8">
        <div className="bg-card border border-border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-bold mb-6 text-foreground flex items-center gap-2">
            <Briefcase className="text-primary" size={20} /> Job Details
          </h2>
          
          <div className="space-y-6">
            <div>
              <label className="block text-sm font-medium mb-2 text-muted-foreground">Job Title</label>
              <input 
                name="title"
                required
                value={formData.title}
                onChange={handleChange}
                className="w-full bg-secondary/30 border border-border rounded-lg px-4 py-3 text-foreground focus:ring-2 focus:ring-primary/50 focus:border-primary focus:outline-none transition-all placeholder:text-muted-foreground"
                placeholder="e.g. Senior Frontend Engineer"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-2 text-muted-foreground">Job Type</label>
                <select
                  name="job_type"
                  value={formData.job_type}
                  onChange={handleChange}
                  className="w-full bg-secondary/30 border border-border rounded-lg px-4 py-3 text-foreground focus:ring-2 focus:ring-primary/50 focus:border-primary focus:outline-none transition-all appearance-none"
                >
                  <option value="full-time">Full-time</option>
                  <option value="part-time">Part-time</option>
                  <option value="contract">Contract</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium mb-2 text-muted-foreground">Work Mode</label>
                <select
                  name="work_mode"
                  value={formData.work_mode}
                  onChange={handleChange}
                  className="w-full bg-secondary/30 border border-border rounded-lg px-4 py-3 text-foreground focus:ring-2 focus:ring-primary/50 focus:border-primary focus:outline-none transition-all appearance-none"
                >
                  <option value="remote">Remote</option>
                  <option value="hybrid">Hybrid</option>
                  <option value="onsite">Onsite</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-2 text-muted-foreground">Experience Level</label>
                <select
                  name="experience_level"
                  value={formData.experience_level}
                  onChange={handleChange}
                  className="w-full bg-secondary/30 border border-border rounded-lg px-4 py-3 text-foreground focus:ring-2 focus:ring-primary/50 focus:border-primary focus:outline-none transition-all appearance-none"
                >
                  <option value="entry">Entry Level</option>
                  <option value="mid">Mid Level</option>
                  <option value="senior">Senior Level</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium mb-2 text-muted-foreground">Salary Range</label>
                <input 
                  name="salary_range"
                  value={formData.salary_range}
                  onChange={handleChange}
                  className="w-full bg-secondary/30 border border-border rounded-lg px-4 py-3 text-foreground focus:ring-2 focus:ring-primary/50 focus:border-primary focus:outline-none transition-all placeholder:text-muted-foreground"
                  placeholder="e.g. ₹12L - ₹18L"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium mb-2 text-muted-foreground">Location</label>
              <div className="relative">
                <MapPin className="absolute left-3 top-3.5 text-muted-foreground" size={16} />
                <input 
                  name="location"
                  value={formData.location}
                  onChange={handleChange}
                  className="w-full bg-secondary/30 border border-border rounded-lg pl-10 pr-4 py-3 text-foreground focus:ring-2 focus:ring-primary/50 focus:border-primary focus:outline-none transition-all placeholder:text-muted-foreground"
                  placeholder="e.g. Kochi, Kerala"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium mb-2 text-muted-foreground">Required Skills</label>
              <div className="space-y-3">
                <div className="flex flex-wrap gap-2 min-h-[40px] p-3 bg-secondary/10 rounded-lg border border-border">
                  {formData.skills_required.map((skill) => (
                    <span key={skill} className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-primary/10 border border-primary/20 text-primary text-sm font-medium">
                      {skill}
                      <button type="button" onClick={() => removeSkill(skill)} className="hover:text-destructive transition-colors"><X size={14} /></button>
                    </span>
                  ))}
                  <input 
                    value={skillInput}
                    onChange={(e) => setSkillInput(e.target.value)}
                    onKeyDown={addSkill}
                    className="flex-1 bg-transparent border-none focus:ring-0 text-foreground min-w-[120px] text-sm placeholder:text-muted-foreground"
                    placeholder="Type skill & press Enter..."
                  />
                </div>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium mb-2 text-muted-foreground">
                Description <span className="text-xs opacity-70 ml-1">({formData.description.length} chars)</span>
              </label>
              <textarea 
                name="description"
                required
                value={formData.description}
                onChange={handleChange}
                rows={8}
                className="w-full bg-secondary/30 border border-border rounded-lg px-4 py-3 text-foreground focus:ring-2 focus:ring-primary/50 focus:border-primary focus:outline-none transition-all resize-none placeholder:text-muted-foreground"
                placeholder="Describe the role, responsibilities, and requirements..."
              />
            </div>
          </div>
        </div>

        <button 
          type="submit"
          disabled={loading}
          className="w-full py-4 bg-primary text-primary-foreground font-bold rounded-xl hover:bg-primary/90 transition-all shadow-[0_0_20px_rgba(59,130,246,0.4)] disabled:opacity-70 disabled:cursor-not-allowed flex items-center justify-center gap-2"
        >
          {loading ? <Loader2 size={20} className="animate-spin" /> : <Save size={20} />}
          <span>Publish Job Post</span>
        </button>
      </form>

      {/* Preview */}
      <div className="space-y-6">
        <div className="flex items-center gap-2 text-muted-foreground mb-2">
          <Eye size={18} />
          <span className="text-sm font-bold uppercase tracking-wider">Live Preview</span>
        </div>

        <div className="sticky top-24">
          <div className="p-6 rounded-xl border border-border bg-card shadow-lg relative overflow-hidden">
            <div className="flex gap-6 mb-6">
              <div className="w-16 h-16 rounded-lg bg-secondary border border-border flex items-center justify-center shrink-0">
                <Building2 size={32} className="text-muted-foreground" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-foreground mb-1">{formData.title || "Job Title"}</h3>
                <div className="flex flex-wrap items-center gap-3 text-sm text-muted-foreground font-medium">
                  <span className="flex items-center gap-1"><Building2 size={14} /> {companyName}</span>
                  <span className="flex items-center gap-1"><MapPin size={14} /> {formData.location}</span>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4 mb-6">
              <div className="p-3 rounded-lg bg-secondary/30 border border-border">
                <div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-1">Salary</div>
                <div className="text-sm font-bold text-foreground">{formData.salary_range || "Not Disclosed"}</div>
              </div>
              <div className="p-3 rounded-lg bg-secondary/30 border border-border">
                <div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-1">Type</div>
                <div className="text-sm font-bold text-foreground capitalize">{formData.job_type}</div>
              </div>
            </div>

            <div className="space-y-4 mb-6">
              <div>
                <h4 className="font-bold text-foreground text-sm mb-2">Required Skills</h4>
                <div className="flex flex-wrap gap-2">
                  {formData.skills_required.length > 0 ? (
                    formData.skills_required.map(skill => (
                      <span key={skill} className="px-2 py-1 rounded bg-secondary border border-border text-xs font-medium text-foreground">
                        {skill}
                      </span>
                    ))
                  ) : (
                    <span className="text-xs text-muted-foreground italic">Skills will appear here...</span>
                  )}
                </div>
              </div>

              <div>
                <h4 className="font-bold text-foreground text-sm mb-2">About the Role</h4>
                <p className="text-sm text-muted-foreground leading-relaxed line-clamp-6">
                  {formData.description || "Job description will appear here..."}
                </p>
              </div>
            </div>

            <button className="w-full py-3 bg-primary text-primary-foreground font-bold rounded-lg opacity-50 cursor-not-allowed">
              Apply Now
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
